repo:
  - ./*
test:
  - testsuite/**/*
microsoft:
  - "**/mssqlserver*/**/*"
  - "**/microsoft/**/*"
oracle:
  - "**/oracle/**/*"
  - "**/oracle-*/**/*"
postgresql:
  - "**/postgresql/**/*"
  - "**/postgresql-*/**/*"
mariadb:
  - "**/mariadb/**/*"
  - "**/mariadb-*/**/*"
mysql:
  - "**/mysql/**/*"
  - "**/mysql-*/**/*"
documentation:
  - doc/**/*
h2database:
  - "**/h2database/**/*"
  - "**/h2database-*/**/*"
db2:
  - "**/db2/**/*"
  - "**/db2-*/**/*"
